### PR TITLE
Remove broken build options

### PR DESCRIPTION
**Pull request by AJenbo**
Sad to see that support for non-Windows was broken to save 0.1% lines of code https://github.com/julealgon/DiabloCore/pull/5

Might as well remove all of it since it's none functional at this point. So much for your complaints about not supporting OSs that the developers don't use I guess.

### CODE REVIEW

**Comment by julealgon** [comment]
> Sad to see that support for non-Windows was broken to save 0.1% lines of code https://github.com/julealgon/DiabloCore/pull/5

I think you are just missing the bigger picture on this. None of this code will remain as is (certainly not cmake) as I make the move to C#. I was just trying to trim as much as I could to remove anything out of the way for the migration. I didn't know upfront how many lines of code each of those things would really be, and that's a secondary concern really.

> Might as well remove all of it since it's none functional at this point. 

Only reason I didn't remove this was because I didn't know 100% if I could. I appreciate you doing it.

> So much for your complaints about not supporting OSs that the developers don't use I guess.

I'm not quite sure what you mean here.

**Comment by AJenbo** [comment]
Glad you like the cleanup :)

> I'm not quite sure what you mean here.

I just remember you complaining that Linux developers don't go out of there way to support Windows. So it seamed ironic that you actively removing Linux support.

I don't think I'm missing the big picture, just being pessimistic. But hey, maybe this will end up as the first C# application I encounter with enough build instructions that I can actually run it outside of Windows :D

**Comment by julealgon** [comment]
> I just remember you complaining that Linux developers don't go out of there way to support Windows. So it seamed ironic that you actively removing Linux support.

Well currently, I'm not going out of my way to support anything in the C++ stack really 😆 I'm completely ignorant on cmake, so I just wanted to minimize noise as much as I could so that whatever remained was easier for me to parse for the conversion later.

> I don't think I'm missing the big picture, just being pessimistic. But hey, maybe this will end up as the first C# application I encounter with enough build instructions that I can actually run it outside of Windows :D

Hopefully that should be the case. I'm looking into using the Monogame engine for the C# version (doing a few tests with it at the moment), and that is portable.

C# has been portable for several years at this point so it surprises me that you've had such bad luck in finding a portable project created with it.

**Comment by AJenbo** [comment]
> C# has been portable for several years at this point so it surprises me that you've had such bad luck in finding a portable project created with it.

I'm aware, C# proponents keeps telling me. But so fare no one I have med have actually used it or know how to set it up since they all just use Windows. I haven't looked in to it myself either, all I have concluded is that it isn't as simple as downloading Visual Code and clicking build which is what I was told by someone that never tried.

**Pull request merged**
